version: '3.8'

services:
  flask-musescore:
    build: .
    container_name: flask-musescore-app
    ports:
      - "8129:8129"
    volumes:
      - ./:/app
      - ./scores:/app/scores
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
