version: '3.8'

services:
  flask-musescore:
    build: .
    volumes:
      - ./:/app
      - ./scores:/app/scores
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: flask-musescore-lb
    ports:
      - "8129:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-musescore
    restart: unless-stopped
